# Generated by Django 4.2.7 on 2023-11-23 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(choices=[('spaghetti', 'Spaghetti'), ('pepperoni_pizza', 'Pepperoni Pizza'), ('bread', 'Bread'), ('ofada_rice', 'Ofada Rice'), ('iguana_on_a_stick', 'Iguana On A Stick')], default='Ofada Rice', max_length=50)),
                ('food_quantity', models.PositiveIntegerField(default=1)),
                ('drink', models.CharField(choices=[('pepsi', 'Pepsi'), ('water', 'Water'), ('xander', 'Xander'), ('nuka_cola', 'Nuka Cola')], default='Water', max_length=50)),
                ('drink_quantity', models.PositiveIntegerField(default=1)),
                ('ordered_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
