# Generated by Django 4.2.7 on 2023-11-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='drink',
            field=models.CharField(choices=[('pepsi', 'Pepsi'), ('water', 'Water'), ('xander', 'Xander'), ('nuka_cola', 'Nuka Cola')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.CharField(choices=[('spaghetti', 'Spaghetti'), ('pepperoni_pizza', 'Pepperoni Pizza'), ('bread', 'Bread'), ('ofada_rice', 'Ofada Rice'), ('iguana_on_a_stick', 'Iguana On A Stick')], max_length=50),
        ),
    ]
